In [1]:
import numpy as np


In [4]:
l=[1,2,3,4,5,6]

In [5]:
np.array(l)

array([1, 2, 3, 4, 5, 6])

In [6]:
l1=[4,5,6,7,"sudh",34.565,True]

In [12]:
a1=np.array(l1)

In [11]:
a2=np.array([[1,2,3],[4,5,6]])

In [10]:
a3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [13]:
a1

array(['4', '5', '6', '7', 'sudh', '34.565', 'True'], dtype='<U32')

In [14]:

a2

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [16]:
#show dimensions when used ndim functions
a1.ndim

1

In [17]:
a2.ndim

2

In [18]:
a3.ndim

3

In [38]:
#it wil show size
a1.size

7

In [20]:
a2.size

6

In [21]:
a3.size

9

In [22]:
a1.shape

(7,)

In [25]:
#2 rows and three columns
a2.shape

(2, 3)

In [26]:
#z=1or matrics and 3 rows and 3 columns
a3.shape

(1, 3, 3)

In [27]:
a1

array(['4', '5', '6', '7', 'sudh', '34.565', 'True'], dtype='<U32')

In [28]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [34]:
#generate random no 
np.random.randint(2,50)

10

In [35]:
#it will generate in thw from of array 3 rows nad 4 columns
np.random.randint(2,50,(3,4))

array([[ 3, 16, 46, 47],
       [34,  8, 49, 30],
       [16, 44, 47, 44]])

In [36]:
#2 matrics in which3 rwos and 4 columns
np.random.randint(2,50,(2,3,4))

array([[[28, 14, 21,  6],
        [27, 13, 46, 32],
        [11,  7,  5,  8]],

       [[21, 43, 43, 40],
        [37, 34, 17, 49],
        [49, 12, 34, 23]]])

In [39]:
np.random.rand(2,3)

array([[0.97038544, 0.48745786, 0.65429824],
       [0.21578829, 0.43543482, 0.10460327]])

In [41]:
a4=np.random.randn(4,4)

In [42]:
a4

array([[-0.15706221, -0.26093947, -0.70544266, -1.14833796],
       [-0.70415138,  0.85485135,  1.22979162,  0.24542355],
       [ 0.2441575 , -0.18243557,  0.93288787,  0.57649658],
       [-1.07392816,  2.24097436, -0.08372585,  0.59001787]])

In [43]:
a4.reshape(3,4)

ValueError: cannot reshape array of size 16 into shape (3,4)

In [44]:
a4.reshape(2,8)

array([[-0.15706221, -0.26093947, -0.70544266, -1.14833796, -0.70415138,
         0.85485135,  1.22979162,  0.24542355],
       [ 0.2441575 , -0.18243557,  0.93288787,  0.57649658, -1.07392816,
         2.24097436, -0.08372585,  0.59001787]])

In [45]:
a4.reshape(8,2)

array([[-0.15706221, -0.26093947],
       [-0.70544266, -1.14833796],
       [-0.70415138,  0.85485135],
       [ 1.22979162,  0.24542355],
       [ 0.2441575 , -0.18243557],
       [ 0.93288787,  0.57649658],
       [-1.07392816,  2.24097436],
       [-0.08372585,  0.59001787]])

In [46]:
a4.reshape(16,1)

array([[-0.15706221],
       [-0.26093947],
       [-0.70544266],
       [-1.14833796],
       [-0.70415138],
       [ 0.85485135],
       [ 1.22979162],
       [ 0.24542355],
       [ 0.2441575 ],
       [-0.18243557],
       [ 0.93288787],
       [ 0.57649658],
       [-1.07392816],
       [ 2.24097436],
       [-0.08372585],
       [ 0.59001787]])

In [47]:
a4.reshape(1,16)

array([[-0.15706221, -0.26093947, -0.70544266, -1.14833796, -0.70415138,
         0.85485135,  1.22979162,  0.24542355,  0.2441575 , -0.18243557,
         0.93288787,  0.57649658, -1.07392816,  2.24097436, -0.08372585,
         0.59001787]])

In [48]:
a4.reshape(2,-1)

array([[-0.15706221, -0.26093947, -0.70544266, -1.14833796, -0.70415138,
         0.85485135,  1.22979162,  0.24542355],
       [ 0.2441575 , -0.18243557,  0.93288787,  0.57649658, -1.07392816,
         2.24097436, -0.08372585,  0.59001787]])

In [49]:
a4.reshape(2,2,4)

array([[[-0.15706221, -0.26093947, -0.70544266, -1.14833796],
        [-0.70415138,  0.85485135,  1.22979162,  0.24542355]],

       [[ 0.2441575 , -0.18243557,  0.93288787,  0.57649658],
        [-1.07392816,  2.24097436, -0.08372585,  0.59001787]]])

In [50]:
a4.reshape(1,1,1,1,1,1,1,2,2,4)

array([[[[[[[[[[-0.15706221, -0.26093947, -0.70544266,
                -1.14833796],
               [-0.70415138,  0.85485135,  1.22979162,
                 0.24542355]],

              [[ 0.2441575 , -0.18243557,  0.93288787,
                 0.57649658],
               [-1.07392816,  2.24097436, -0.08372585,
                 0.59001787]]]]]]]]]])

In [51]:
a1


array(['4', '5', '6', '7', 'sudh', '34.565', 'True'], dtype='<U32')

In [52]:
a1[0]

'4'

In [53]:
a1[2:6]

array(['6', '7', 'sudh', '34.565'], dtype='<U32')

In [54]:
a1[2:6:2]

array(['6', 'sudh'], dtype='<U32')

In [55]:
a1[::-1]

array(['True', '34.565', 'sudh', '7', '6', '5', '4'], dtype='<U32')

In [58]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
a2[0]

array([1, 2, 3])

In [60]:
a2[:,1:]

array([[2, 3],
       [5, 6]])

In [61]:
a2[:,[1,2]]

array([[2, 3],
       [5, 6]])

In [62]:
a2[[0,1],1:]

array([[2, 3],
       [5, 6]])

In [66]:
a5=np.random.randint(2,90,(6,5))

In [67]:
a5

array([[85, 52, 45, 10, 34],
       [36, 52, 16, 33, 28],
       [34, 72, 79,  8, 62],
       [55, 83, 83, 83, 88],
       [60, 38,  7, 67, 61],
       [65, 64, 70, 52, 41]])

In [68]:
#to generate data having value greater than 40
a5[a5>40]

array([85, 52, 45, 52, 72, 79, 62, 55, 83, 83, 83, 88, 60, 67, 61, 65, 64,
       70, 52, 41])

In [69]:
a5

array([[85, 52, 45, 10, 34],
       [36, 52, 16, 33, 28],
       [34, 72, 79,  8, 62],
       [55, 83, 83, 83, 88],
       [60, 38,  7, 67, 61],
       [65, 64, 70, 52, 41]])

In [70]:
#to change the values at partiuclar insatnces
a5[0,1]=500

In [71]:
a5

array([[ 85, 500,  45,  10,  34],
       [ 36,  52,  16,  33,  28],
       [ 34,  72,  79,   8,  62],
       [ 55,  83,  83,  83,  88],
       [ 60,  38,   7,  67,  61],
       [ 65,  64,  70,  52,  41]])

In [72]:
a6=np.random.randint(0,3,(3,3))

In [73]:
a7=np.random.randint(0,3,(3,3))

In [74]:
a6

array([[2, 1, 0],
       [0, 2, 0],
       [2, 0, 1]])

In [75]:
a7

array([[1, 0, 1],
       [2, 2, 0],
       [0, 2, 1]])

In [76]:
#element matrix multipication
a6*a7

array([[2, 0, 0],
       [0, 4, 0],
       [0, 0, 1]])

In [77]:
#   @is used to do multiplication between 2 matrix
a6@a7

array([[4, 2, 2],
       [4, 4, 0],
       [2, 2, 3]])

In [78]:
a6+100

array([[102, 101, 100],
       [100, 102, 100],
       [102, 100, 101]])

In [79]:
a6*2

array([[4, 2, 0],
       [0, 4, 0],
       [4, 0, 2]])

In [80]:
a6/0

C:\Users\acer\AppData\Local\Temp/ipykernel_4432/1058679823.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a6/0
C:\Users\acer\AppData\Local\Temp/ipykernel_4432/1058679823.py:1: RuntimeWarning: invalid value encountered in true_divide
  a6/0


array([[inf, inf, nan],
       [nan, inf, nan],
       [inf, nan, inf]])

In [81]:
a6

array([[2, 1, 0],
       [0, 2, 0],
       [2, 0, 1]])

In [82]:
a6**3

array([[8, 1, 0],
       [0, 8, 0],
       [8, 0, 1]], dtype=int32)

In [84]:
a8=np.zeros((4,4))

In [85]:
a9=np.ones((4,5))

In [86]:
a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [87]:
a8

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [88]:

a9+10

array([[11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.]])

In [89]:
#it wil do operation in rows
a9+np.array([1,2,3,4,5])

array([[2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.]])

In [90]:
#lesser element will give error need atleast 5 elements
a9+np.array([1,2,3,4])

ValueError: operands could not be broadcast together with shapes (4,5) (4,) 

In [91]:
a9+np.array([1,2,3,4,5])

array([[2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.]])

In [93]:
#should we inclosed with double bracket otherwise it will give error
np.array([[1,2,3,4]]).T + a9

array([[2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.]])

In [94]:
a6


array([[2, 1, 0],
       [0, 2, 0],
       [2, 0, 1]])

In [96]:
#transpose ( reverse with rows and columns)
a6.T

array([[2, 0, 2],
       [1, 2, 0],
       [0, 0, 1]])

In [97]:
np.sqrt(a5)

array([[ 9.21954446, 22.36067977,  6.70820393,  3.16227766,  5.83095189],
       [ 6.        ,  7.21110255,  4.        ,  5.74456265,  5.29150262],
       [ 5.83095189,  8.48528137,  8.88819442,  2.82842712,  7.87400787],
       [ 7.41619849,  9.11043358,  9.11043358,  9.11043358,  9.38083152],
       [ 7.74596669,  6.164414  ,  2.64575131,  8.18535277,  7.81024968],
       [ 8.06225775,  8.        ,  8.36660027,  7.21110255,  6.40312424]])

In [98]:
a5

array([[ 85, 500,  45,  10,  34],
       [ 36,  52,  16,  33,  28],
       [ 34,  72,  79,   8,  62],
       [ 55,  83,  83,  83,  88],
       [ 60,  38,   7,  67,  61],
       [ 65,  64,  70,  52,  41]])

In [99]:
np.exp(a5)

array([[8.22301271e+036, 1.40359222e+217, 3.49342711e+019,
        2.20264658e+004, 5.83461743e+014],
       [4.31123155e+015, 3.83100800e+022, 8.88611052e+006,
        2.14643580e+014, 1.44625706e+012],
       [5.83461743e+014, 1.85867175e+031, 2.03828107e+034,
        2.98095799e+003, 8.43835667e+026],
       [7.69478527e+023, 1.11286375e+036, 1.11286375e+036,
        1.11286375e+036, 1.65163625e+038],
       [1.14200739e+026, 3.18559318e+016, 1.09663316e+003,
        1.25236317e+029, 3.10429794e+026],
       [1.69488924e+028, 6.23514908e+027, 2.51543867e+030,
        3.83100800e+022, 6.39843494e+017]])

In [100]:
np.log10(a5)

array([[1.92941893, 2.69897   , 1.65321251, 1.        , 1.53147892],
       [1.5563025 , 1.71600334, 1.20411998, 1.51851394, 1.44715803],
       [1.53147892, 1.8573325 , 1.89762709, 0.90308999, 1.79239169],
       [1.74036269, 1.91907809, 1.91907809, 1.91907809, 1.94448267],
       [1.77815125, 1.5797836 , 0.84509804, 1.8260748 , 1.78532984],
       [1.81291336, 1.80617997, 1.84509804, 1.71600334, 1.61278386]])

In [101]:
range(0,10)

range(0, 10)

In [102]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [105]:
#in numpy arange function works with float values
np.arange(1,10.5,2.5)

array([1. , 3.5, 6. , 8.5])

In [107]:
np.linspace(2,3,num=50,retstep=True)

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 0.02040816326530612)

In [108]:
np.logspace(2,4,num=4,base=10)

array([  100.        ,   464.15888336,  2154.43469003, 10000.        ])

In [109]:
#it will assign the values in diagnally 
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [116]:
import cufflinks as cf
import numpy as np
import pandas as pd
import seaborn as sns

In [118]:
cf.go_offline()

In [119]:
np.random.randn(100,3)

array([[-3.13651574e-01, -5.43811898e-01, -2.32097318e+00],
       [ 1.30984809e+00, -1.05761186e+00,  3.89721864e-01],
       [-4.16472054e-01,  8.49657196e-01, -5.29526967e-01],
       [-1.49244260e-01,  5.84134709e-01,  4.41903808e-01],
       [-1.46192160e+00,  1.01757343e+00,  3.04873865e-01],
       [ 6.09289719e-01, -2.19602490e-01, -3.87164628e-01],
       [-7.61559542e-01, -3.59304117e-01, -2.98823169e+00],
       [-4.29123559e-01,  1.06569296e+00, -4.23136582e-01],
       [-3.64453075e-01, -9.51329125e-01,  1.01264742e+00],
       [ 3.32032840e-01, -1.12251284e+00, -7.06372480e-01],
       [ 9.16086442e-01,  1.80108158e+00,  2.41258057e-01],
       [ 4.52488695e-01, -2.16882414e+00,  1.11796048e+00],
       [ 6.15815626e-02,  4.77382418e-01, -1.28556872e+00],
       [-8.80674191e-01, -7.66554760e-01, -7.11124346e-02],
       [-2.65551874e-01, -1.11240911e+00,  2.62409324e-01],
       [ 5.50831257e-01,  1.54140659e+00,  1.32146337e-01],
       [ 1.61080347e-01,  1.79785097e-01

In [122]:
pd.DataFrame(np.random.randn(100,3),columns=['A','B','C'])

A         B         C
0  -0.035911 -0.996177  0.849914
1   0.221081 -1.279412  0.550332
2   1.258701  0.011953  1.042650
3  -0.287760  0.313037 -1.215683
4  -2.175451  0.183920 -0.250139
..       ...       ...       ...
95  2.036327 -0.455521  0.475611
96  0.102981 -0.716105 -0.765924
97  0.517508  0.169127 -0.397005
98 -0.677448 -1.031105  0.903296
99 -0.758998 -1.120235  0.462462

[100 rows x 3 columns]

In [123]:
df=pd.DataFrame(np.random.randn(100,3),columns=['A','B','C'])

In [125]:
df.iplot()

In [128]:
df1=pd.DataFrame(np.random.randint(3,100,(100,1)))

In [130]:
df1.iplot()

In [131]:
df

A         B         C
0   0.009643  0.099545 -0.656580
1  -0.090869 -0.549173  0.164121
2   1.144125 -0.904338  1.003405
3  -0.098524  0.277816  1.486235
4   0.331333 -0.276256  0.185281
..       ...       ...       ...
95 -0.373412 -0.532969  1.368738
96 -0.213100 -0.301682  0.482680
97 -0.267741  0.339052 -2.035571
98 -0.057216 -0.371584  0.671007
99  0.683075 -0.121611 -0.219424

[100 rows x 3 columns]

In [132]:
df.iplot(x='A',y='B',mode='markers')

In [134]:
df2=sns.load_dataset('titanic')

In [135]:
df2.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [137]:
df2.iplot(x='age',y='fare',mode='markers')

In [138]:
df2.iplot(x='age',y='pclass',mode='markers')

In [139]:
df2.iplot(x='fare',y='pclass',mode='markers')

In [140]:
df2.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [141]:
df2.iplot(kind='bar',x='sex',y='survived')

In [ ]:
s